### ISSUE TITLE
Code formatter

### ISSUE THREAD

**Issue by pDiller** [pDiller/JiraAlerts#6]
We should find a code-formatter for this projekt. So we all have same code Style.

**Comment by matthiasbalke** [comment]
How about Google Code Formatter and [Spotless Gradle Plugin](https://github.com/diffplug/spotless): https://github.com/reflectoring/infiniboard/blob/master/gradle.d/30-java.gradle#L37


This will allow you to verify the format and format the code by using gradle tasks.

**Comment by pDiller** [comment]
Maybe you can show me tomorrow how it works, sounds like an great idea 👍

**Comment by pDiller** [comment]
Done.
